# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Carlos's Blog 
email: baudin-sky@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  I have been consuming the combined knowledge of my heroes for years. Now, after over 20 years as a software developer, I am ready to give back to everyone. I hope you enjoy!
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://baudin999.github.io/blog/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Baudin999 
linkedin: https://www.linkedin.com/in/carlos-k-4016b8225/
github: https://github.com/baudin999
future: true
include:
    - extra
    - scholar

scholar:
  bibliography_template: bib
  style: apa
  locale: en


collections:
  populism:
    output: true

hydejack:
  paginate: 50
  dark_mode:
    dynamic: true
    sunrise: 60
    sunset: 180
    icon: true
    always: true 

author:
  name: Carlos Kelkboom
  email: baudin-sky@pm.me
  picture: /blog/assets/img/self.jfif
  about: |
   Hi, I'm Carlos, and I've been a software developer for over 20 years. I've learned a lot 
   from blog posts, Stack Overflow, and YouTube, but I've never felt confident enough to share 
   my knowledge and give back to the community.

   This blog is my attempt to return the favor and give back to the community.

menu:
  - title: Résumé 
    url: /resume/
  - title: About me
    url: /about/

# theme configurations
theme: jekyll-theme-hydejack
accent_image: /blog/assets/img/site_bg.jpg
accent_color: rgb(45, 16, 9)
theme_color: rgb(45, 16, 9)

plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-scholar

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
