# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Carlos's Blog 
email: baudin@pm.com 
description: >- # this means to ignore newlines until "baseurl:"
  I have been consuming the combined knowledge of my hero's for years. Now, after
  over 20 years as a software developer, I am ready to give back to everyone. I 
  hope you enjoy!
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://baudin999.github.io/blog/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Baudin999 

# Build settings
# theme: minima
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
